<?php

use Illuminate\Database\Seeder;
use App\HubungiKami;
use App\PanduanPengguna;
use App\Penafian;
use App\PenyataanPrivasi;
use App\Faq;
use App\Pengumuman;

class PortalSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        HubungiKami::create(['title'=>'Hubungi Kami','content'=>'MyGeo Explorer sesuai dilayari oleh semua perisian pelayar (Desktop & Versi Mobile) atau mana-mana perisian pelayan web yang setara dengannya. Jika anda menggunakan pelayar versi terdahulu atau selainnya, segelintir paparan tidak dapat dilakukan dengan sempurna. Pelayar web mestilah menyokong penggunaan JavaScript, Cascading Style Sheet, warna, format teks dan fungsi-fungsi asas yang lain. Resolusi minima yang bersesuaian untuk memaparkan laman web ini ialah 1024 x 768 piksel. Muat Turun PDF Panduan Pengguna:']);
        
        PanduanPengguna::create(['title' => "Panduan Pengguna",'content' => "<p>MyGeo <strong>Explorer</strong> <em>sesuai</em> dilayari oleh semua perisian pelayar (Desktop &amp; Versi Mobile) atau mana-mana perisian pelayan web yang setara dengannya. Jika anda menggunakan pelayar versi terdahulu atau selainnya, segelintir paparan tidak dapat dilakukan dengan sempurna. Pelayar web mestilah menyokong penggunaan JavaScript, Cascading Style Sheet, warna, format teks dan fungsi-fungsi asas yang lain.Resolusi minima yang bersesuaian untuk memaparkan laman web ini ialah 1024 x 768 piksel.Muat Turun PDF Panduan Pengguna:</p>"]);

        Penafian::create(['title' => "Penafian",'content' => "Maklumat yang dipaparkan di laman web ini dianggap sebagai maklumat awam dan boleh digunakan, digunakan kembali dan diedarkan secara bebas oleh sesiapa sahaja. Sebarang penggunaan ayat/foto/gambar diminta untuk diberikan kredit. Data untuk Geoportal ini digalakkan diperoleh secara langsung dari sumber yang boleh dipercayai dan bukan melalui sumber lain yang mungkin mengubah data dengan cara tertentu. Walaupun Geoportal ini berusaha sedaya upaya untuk memberikan maklumat yang tepat dan lengkap, pelbagai data seperti nama, nombor telefon, dan lain-lain mungkin berubah sebelum dikemas kini. Administrator Geoportal ini mengalu-alukan cadangan bagaimana untuk memperbaiki halaman utama kami dan membetulkan kesilapan. Geoportal ini tidak memberikan jaminan, tersurat atau tersirat, mengenai ketepatan, kebolehpercayaan atau kelengkapan data yang diberikan."]);

        PenyataanPrivasi::create(['title' => "Penyataan Privasi",'content' => "CONTOH TEKS: Terima kasih kerana melawat dan mengkaji Dasar Privasi dan Keselamatan kami. Dasar privasi kami jelas: Kami tidak akan mengumpulkan maklumat peribadi mengenai anda semasa anda melayari laman web kami melainkan anda memilih untuk memberikan maklumat tersebut kepada kami. Dasar Privasi menggariskan maklumat yang kami kumpulkan melalui Geoportal ini dan bagaimana kami menggunakan maklumat tersebut. Maklumat Dikumpulkan dan Disimpan Secara Automatik. Sekiranya anda tidak melakukan apa-apa semasa lawatan anda melainkan melayari Geoportal ini, membaca halaman, atau mencari maklumat, kami akan mengumpulkan dan menyimpan maklumat tertentu mengenai lawatan anda secara automatik. Maklumat ini tidak mengenal pasti • Nama domain Internet (misalnya, \"xcompany.com\" jika anda menggunakan akaun akses Internet peribadi atau \"yourschool.edu\" jika anda menyambung dari domain universiti) dan alamat IP (alamat IP adalah nombor yang secara automatik diberikan kepada komputer anda setiap kali anda melayari Web) dari mana anda mengakses laman web kami; • Jenis penyemak imbas dan sistem operasi yang digunakan untuk mengakses laman web kami; • Tarikh dan masa anda mengakses laman web kami; • Halaman yang anda lawati; dan • Sekiranya anda memautkan ke Geoportal ini dari laman web lain, alamat laman web tersebut."]);

        Faq::create([
            'title' => "Soalan Lazim (FAQ)",
            'category'=>'METADATA',
            'content' => "Adakah Aplikasi UPI memaparkan carian nombor lot dan maklumat lain berkenaan lot tanah? Tidak. Aplikasi UPI hanya memaparkan struktur kod dan nama sempadan pentadbiran tanah seperti Negeri, Daerah, Mukim/Bandar/Pekan dan Seksyen. Maklumat berkenaan lokasi nombor lot tidak dipaparkan di dalam aplikasi ini. Adakah pengguna perlu mendaftar untuk melayari aplikasi UPI? Tidak. Aplikasi UPI terbuka untuk paparan umum."
        ]);
        Faq::create([
            'title' => "Soalan Lazim (FAQ)",
            'category'=>'PERMOHONAN DATA-DATA ASAS',
            'content' => "Apa itu Data Custodian? Custodian adalah agensi yang bertindak sebagai pemegang amanah (trustee) bagi pihak Kerajaan dan bukan pemilik mutlak data yang terdapat dalam pangkalan data masing-masing. Apa itu Data Geospatial? Maklumat yang mengenal pasti, menggambarkan, atau menerangkan kedudukan geografi, sempadan atau ciri-ciri penduduk serta semula jadi atau fitur yang dibina di atas permukaan dan bawah permukaan bumi."
        ]);

        Pengumuman::create(['kategori' => "Makluman",'title' => "Selamat tahun baru kepada semua pengguna MyGeo Explorer",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-06-02 23:45:09'))]);
        Pengumuman::create(['kategori' => "Peringatan",'title' => "Agensi hendaklah mengemaskini metadata masing-masing",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-06-01 23:45:09'))]);
        Pengumuman::create(['kategori' => "Metadata Baharu",'title' => "Grid for Climate Change Projection for Peninsular Malaysia",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-30 23:45:09'))]);
        Pengumuman::create(['kategori' => "Pengemaskinian",'title' => "Climate Change Projection for Peninsular Malaysia (2010-2099)",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-29 23:45:09'))]);
        Pengumuman::create(['kategori' => "Pengemaskinian",'title' => "Climate Change Projection for Peninsular Malaysia (1999-2009)",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-28 23:45:09'))]);
        Pengumuman::create(['kategori' => "Makluman 2",'title' => "2 Selamat tahun baru kepada semua pengguna MyGeo Explorer",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-27 23:45:09'))]);
        Pengumuman::create(['kategori' => "Peringatan 2",'title' => "2 Agensi hendaklah mengemaskini metadata masing-masing",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-26 23:45:09'))]);
        Pengumuman::create(['kategori' => "Metadata Baharu 2",'title' => "2 Grid for Climate Change Projection for Peninsular Malaysia",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-25 23:45:09'))]);
        Pengumuman::create(['kategori' => "Pengemaskinian 2",'title' => "2 Climate Change Projection for Peninsular Malaysia (2010-2099)",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-24 23:45:09'))]);
        Pengumuman::create(['kategori' => "Pengemaskinian 2",'title' => "2 Climate Change Projection for Peninsular Malaysia (1999-2009)",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-23 23:45:09'))]);
        Pengumuman::create(['kategori' => "Makluman 3",'title' => "3 Selamat tahun baru kepada semua pengguna MyGeo Explorer",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-22 23:45:09'))]);
        Pengumuman::create(['kategori' => "Peringatan 3",'title' => "3 Agensi hendaklah mengemaskini metadata masing-masing",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-21 23:45:09'))]);
        Pengumuman::create(['kategori' => "Metadata Baharu 3",'title' => "3 Grid for Climate Change Projection for Peninsular Malaysia",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-20 23:45:09'))]);
        Pengumuman::create(['kategori' => "Pengemaskinian 3",'title' => "3 Climate Change Projection for Peninsular Malaysia (2010-2099)",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-19 23:45:09'))]);
        Pengumuman::create(['kategori' => "Pengemaskinian 3",'title' => "3 Climate Change Projection for Peninsular Malaysia (1999-2009)",'content'=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",'date'=>date('Y-m-d H:i:s',strtotime('2021-05-18 23:45:09'))]);
    }
}
