<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Auth;

class XmlController extends Controller {

    function __construct() {}

    public function createXml($request,$fileUrl="",$keywords="",$topicCategories="",$custom_inputs="") {
        $c2_metadataName = strtoupper($request->c2_metadataName);
        $c2_abstract = trim(preg_replace('/\s+/',' ',$request->c2_abstract));
        $xml = <<<XML
                <MD_Metadata
                    xmlns:gmd="http://www.isotc211.org/2005/gmd"
                    xmlns:gco="http://www.isotc211.org/2005/gco"
                    xmlns:gml="http://www.opengis.net/gml" 
                    xmlns:xlink="http://www.w3.org/1999/xlink" 
                    xmlns:srv="http://www.isotc211.org/2005/srv"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://www.isotc211.org/2005/gmd/metadataEntity.xsd">
                    <fileIdentifier>
                        <gco:CharacterString>{82EB5705-61EA-41A7-BAF5-183B3B3EA010}</gco:CharacterString>
                    </fileIdentifier>
                    <language>
                        <gco:CharacterString>$request->flanguage</gco:CharacterString>
                    </language>
                    <characterSet>
                        <MD_CharacterSetCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_CharacterSetCode" codeListValue="8859part3">8859part3</MD_CharacterSetCode>
                    </characterSet>
                    <hierarchyLevel>
                        <MD_ScopeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue="$request->kategori">$request->kategori</MD_ScopeCode>
                    </hierarchyLevel>
                    <contact>
                        <CI_ResponsibleParty>
                            <contentInfo>
                                <gco:CharacterString>$request->c1_content_info</gco:CharacterString>
                            </contentInfo>
                            <organisationName>
                                <gco:CharacterString>$request->publisher_agensi_organisasi</gco:CharacterString>
                            </organisationName>
                            <departmentName>
                                <gco:CharacterString>$request->publisher_bahagian</gco:CharacterString>
                            </departmentName>
                            <individualName>
                                <gco:CharacterString>$request->publisher_name</gco:CharacterString>
                            </individualName>
                            <role>
                                <CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="custodian">$request->publisher_role</CI_RoleCode>
                            </role>
                            <contactInfo>
                                <CI_Contact>
                                    <phone>
                                        <CI_Telephone>
                                            <voice>
                                                <gco:CharacterString>$request->publisher_phone</gco:CharacterString>
                                            </voice>
                                        </CI_Telephone>
                                    </phone>
                                    <address>
                                        <CI_Address>
                                            <electronicMailAddress>
                                                <gco:CharacterString>$request->publisher_email</gco:CharacterString>
                                            </electronicMailAddress>
                                        </CI_Address>
                                    </address>
                                </CI_Contact>
                            </contactInfo>
                        </CI_ResponsibleParty>
                    </contact>
                    <dateStamp>
                        <gco:Date>2013-03-05</gco:Date>
                    </dateStamp>
                    <metadataStandardName>
                        <gco:CharacterString>MyGDI Metadata Standard (Dataset)</gco:CharacterString>
                    </metadataStandardName>
                    <metadataStandardVersion>
                        <gco:CharacterString>Version 1.0 2011</gco:CharacterString>
                    </metadataStandardVersion>
                    <metadataMaintenance>
                        <MD_MaintenanceInformation>
                            <maintenanceAndUpdateFrequency>
                                <MD_MaintenanceFrequencyCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_MaintenanceFrequencyCode" codeListValue="">$request->c12_maintenanceUpdate</MD_MaintenanceFrequencyCode>
                            </maintenanceAndUpdateFrequency>
                        </MD_MaintenanceInformation>
                    </metadataMaintenance>
                    <referenceSystemInfo>
                        <MD_ReferenceSystem>
                            <referenceSystemIdentifier>
                                <RS_Identifier>
                                    <codeSpace>
                                        <gco:CharacterString>$request->c13_ref_sys_identify</gco:CharacterString>
                                    </codeSpace>
                                </RS_Identifier>
                            </referenceSystemIdentifier>
                        </MD_ReferenceSystem>
                        <MD_CRS>
                            <projection>
                                <RS_Identifier>
                                    <codeSpace>
                                        <gco:CharacterString>$request->c13_projection</gco:CharacterString>
                                    </codeSpace>
                                </RS_Identifier>
                            </projection>
                            <ellipsoid>
                                <RS_Identifier>
                                    <codeSpace>
                                        <gco:CharacterString>$request->c13_ellipsoid</gco:CharacterString>
                                    </codeSpace>
                                </RS_Identifier>
                            </ellipsoid>
                            <datum>
                                <RS_Identifier>
                                    <codeSpace>
                                        <gco:CharacterString>$request->c13_datum</gco:CharacterString>
                                    </codeSpace>
                                </RS_Identifier>
                            </datum>
                            <ellipsoidParameters>
                                <MD_EllipsoidParameters>
                                    <semiMajorAxis>
                                        <gco:CharacterString>$request->c13_semi_major_axis</gco:CharacterString>
                                    </semiMajorAxis>
                                    <axisUnits>
                                        <gco:UomLength>$request->c13_axis_units Meter</gco:UomLength>
                                    </axisUnits>
                                    <denominatorOfFlatteningRatio>
                                        <gco:CharacterString>$request->c13_denom_flat_ratio</gco:CharacterString>
                                    </denominatorOfFlatteningRatio>
                                </MD_EllipsoidParameters>
                            </ellipsoidParameters>
                        </MD_CRS>
                    </referenceSystemInfo>
                    <contentInfo>
                        <MD_FeatureCatalogueDescription>
                            <complianceCode>
                                <gco:Boolean/>
                            </complianceCode>
                            <language>
                                <gco:CharacterString/>
                            </language>
                            <featureCatalogueCitation>
                                <CI_Citation>
                                    <edition>
                                        <gco:CharacterString/>
                                    </edition>
                                    <editionDate>
                                        <gco:Date>1970</gco:Date>
                                    </editionDate>
                                </CI_Citation>
                            </featureCatalogueCitation>
                        </MD_FeatureCatalogueDescription>
                    </contentInfo>
                    <identificationInfo> 
                        <MD_DataIdentification>
                            <citation>
                                <CI_Citation>
                                    <title>
                                        <gco:CharacterString>$c2_metadataName</gco:CharacterString>
                                    </title>
                                    <date>
                                        <CI_Date>
                                            <date>
                                                <gco:Date>$request->c2_metadataDate</gco:Date>
                                            </date>
                                            <dateType>
                                                <CI_DateTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="creation">$request->c2_metadataDateType</CI_DateTypeCode>
                                            </dateType>
                                        </CI_Date>
                                    </date>
                                    <series>
                                        <CI_Series></CI_Series>
                                    </series>
                                </CI_Citation>
                            </citation>
                            <metadataStatus>
                                <gco:CharacterString>$request->c2_metadataStatus</gco:CharacterString>
                            </metadataStatus>
                            <gmd:typeOfServices>
                                <gco:CharacterString>$request->c2_typeOfServices</gco:CharacterString>
                            </gmd:typeOfServices>
                            <gmd:serviceUrl>
                                <gco:CharacterString>$request->c2_serviceUrl</gco:CharacterString>
                            </gmd:serviceUrl>
                            <gmd:productType>
                                <gmd:productTypeItem>
                                    <gco:CharacterString>$request->c2_product_type</gco:CharacterString>
                                </gmd:productTypeItem>
                            </gmd:productType>
                            <abstract>
                                <gco:CharacterString>$c2_abstract</gco:CharacterString>
                            </abstract>
                            <gmd:abstractApplication_namaAplikasi>
                                <gco:CharacterString>$request->abstractApplication_namaAplikasi</gco:CharacterString>
                            </gmd:abstractApplication_namaAplikasi>
                            <gmd:abstractApplication_tujuan>
                                <gco:CharacterString>$request->abstractApplication_tujuan</gco:CharacterString>
                            </gmd:abstractApplication_tujuan>
                            <gmd:abstractApplication_tahunPembangunan>
                                <gco:CharacterString>$request->abstractApplication_tahunPembangunan</gco:CharacterString>
                            </gmd:abstractApplication_tahunPembangunan>
                            <gmd:abstractApplication_kemaskini>
                                <gco:CharacterString>$request->abstractApplication_kemaskini</gco:CharacterString>
                            </gmd:abstractApplication_kemaskini>
                            <gmd:abstractApplication_dataTerlibat>
                                <gco:CharacterString>$request->abstractApplication_dataTerlibat</gco:CharacterString>
                            </gmd:abstractApplication_dataTerlibat>
                            <gmd:abstractApplication_sasaranPengguna>
                                <gco:CharacterString>$request->abstractApplication_sasaranPengguna</gco:CharacterString>
                            </gmd:abstractApplication_sasaranPengguna>
                            <gmd:abstractApplication_versi>
                                <gco:CharacterString>$request->abstractApplication_versi</gco:CharacterString>
                            </gmd:abstractApplication_versi>
                            <gmd:abstractApplication_perisianDigunaPembangunan>
                                <gco:CharacterString>$request->abstractApplication_perisianDigunaPembangunan</gco:CharacterString>
                            </gmd:abstractApplication_perisianDigunaPembangunan>
                            <gmd:abstractDocument_namaDokumen>
                                <gco:CharacterString>$request->abstractDocument_namaDokumen</gco:CharacterString>
                            </gmd:abstractDocument_namaDokumen>
                            <gmd:abstractDocument_tujuan>
                                <gco:CharacterString>$request->abstractDocument_tujuan</gco:CharacterString>
                            </gmd:abstractDocument_tujuan>
                            <gmd:abstractDocument_tahunTerbitan>
                                <gco:CharacterString>$request->abstractDocument_tahunTerbitan</gco:CharacterString>
                            </gmd:abstractDocument_tahunTerbitan>
                            <gmd:abstractDocument_edisi>
                                <gco:CharacterString>$request->abstractDocument_edisi</gco:CharacterString>
                            </gmd:abstractDocument_edisi>
                            <gmd:abstractGISActivityProject_namaAktiviti>
                                <gco:CharacterString>$request->abstractGISActivityProject_namaAktiviti</gco:CharacterString>
                            </gmd:abstractGISActivityProject_namaAktiviti>
                            <gmd:abstractGISActivityProject_tujuan>
                                <gco:CharacterString>$request->abstractGISActivityProject_tujuan</gco:CharacterString>
                            </gmd:abstractGISActivityProject_tujuan>
                            <gmd:abstractGISActivityProject_lokasi>
                                <gco:CharacterString>$request->abstractGISActivityProject_lokasi</gco:CharacterString>
                            </gmd:abstractGISActivityProject_lokasi>
                            <gmd:abstractGISActivityProject_tahun>
                                <gco:CharacterString>$request->abstractGISActivityProject_tahun</gco:CharacterString>
                            </gmd:abstractGISActivityProject_tahun>
                            <gmd:abstractMap_namaPeta>
                                <gco:CharacterString>$request->abstractMap_namaPeta</gco:CharacterString>
                            </gmd:abstractMap_namaPeta>
                            <gmd:abstractMap_kawasan>
                                <gco:CharacterString>$request->abstractMap_kawasan</gco:CharacterString>
                            </gmd:abstractMap_kawasan>
                            <gmd:abstractMap_tujuan>
                                <gco:CharacterString>$request->abstractMap_tujuan</gco:CharacterString>
                            </gmd:abstractMap_tujuan>
                            <gmd:abstractMap_tahunTerbitan>
                                <gco:CharacterString>$request->abstractMap_tahunTerbitan</gco:CharacterString>
                            </gmd:abstractMap_tahunTerbitan>
                            <gmd:abstractMap_edisi>
                                <gco:CharacterString>$request->abstractMap_edisi</gco:CharacterString>
                            </gmd:abstractMap_edisi>
                            <gmd:abstractMap_noSiri>
                                <gco:CharacterString>$request->abstractMap_noSiri</gco:CharacterString>
                            </gmd:abstractMap_noSiri>
                            <gmd:abstractMap_skala>
                                <gco:CharacterString>$request->abstractMap_skala</gco:CharacterString>
                            </gmd:abstractMap_skala>
                            <gmd:abstractMap_unit>
                                <gco:CharacterString>$request->abstractMap_unit</gco:CharacterString>
                            </gmd:abstractMap_unit>
                            <gmd:abstractRasterData_namaData>
                                <gco:CharacterString>$request->abstractRasterData_namaData</gco:CharacterString>
                            </gmd:abstractRasterData_namaData>
                            <gmd:abstractRasterData_lokasi>
                                <gco:CharacterString>$request->abstractRasterData_lokasi</gco:CharacterString>
                            </gmd:abstractRasterData_lokasi>
                            <gmd:abstractRasterData_rumusanData>
                                <gco:CharacterString>$request->abstractRasterData_rumusanData</gco:CharacterString>
                            </gmd:abstractRasterData_rumusanData>
                            <gmd:abstractRasterData_tujuanData>
                                <gco:CharacterString>$request->abstractRasterData_tujuanData</gco:CharacterString>
                            </gmd:abstractRasterData_tujuanData>
                            <gmd:abstractRasterData_kaedahPenyediaanData>
                                <gco:CharacterString>$request->abstractRasterData_kaedahPenyediaanData</gco:CharacterString>
                            </gmd:abstractRasterData_kaedahPenyediaanData>
                            <gmd:abstractRasterData_format>
                                <gco:CharacterString>$request->abstractRasterData_format</gco:CharacterString>
                            </gmd:abstractRasterData_format>
                            <gmd:abstractRasterData_unit>
                                <gco:CharacterString>$request->abstractRasterData_unit</gco:CharacterString>
                            </gmd:abstractRasterData_unit>
                            <gmd:abstractRasterData_skala>
                                <gco:CharacterString>$request->abstractRasterData_skala</gco:CharacterString>
                            </gmd:abstractRasterData_skala>
                            <gmd:abstractRasterData_statusData>
                                <gco:CharacterString>$request->abstractRasterData_statusData</gco:CharacterString>
                            </gmd:abstractRasterData_statusData>
                            <gmd:abstractRasterData_tahunPerolehan>
                                <gco:CharacterString>$request->abstractRasterData_tahunPerolehan</gco:CharacterString>
                            </gmd:abstractRasterData_tahunPerolehan>
                            <gmd:abstractRasterData_jenisSatelit>
                                <gco:CharacterString>$request->abstractRasterData_jenisSatelit</gco:CharacterString>
                            </gmd:abstractRasterData_jenisSatelit>
                            <gmd:abstractRasterData_format>
                                <gco:CharacterString>$request->abstractRasterData_format</gco:CharacterString>
                            </gmd:abstractRasterData_format>
                            <gmd:abstractRasterData_resolusi>
                                <gco:CharacterString>$request->abstractRasterData_resolusi</gco:CharacterString>
                            </gmd:abstractRasterData_resolusi>
                            <gmd:abstractRasterData_kawasanLitupan>
                                <gco:CharacterString>$request->abstractRasterData_kawasanLitupan</gco:CharacterString>
                            </gmd:abstractRasterData_kawasanLitupan>
                            <gmd:abstractServices_namaServis>
                                <gco:CharacterString>$request->abstractServices_namaServis</gco:CharacterString>
                            </gmd:abstractServices_namaServis>
                            <gmd:abstractServices_lokasi>
                                <gco:CharacterString>$request->abstractServices_lokasi</gco:CharacterString>
                            </gmd:abstractServices_lokasi>
                            <gmd:abstractServices_tujuan>
                                <gco:CharacterString>$request->abstractServices_tujuan</gco:CharacterString>
                            </gmd:abstractServices_tujuan>
                            <gmd:abstractServices_dataTerlibat>
                                <gco:CharacterString>$request->abstractServices_dataTerlibat</gco:CharacterString>
                            </gmd:abstractServices_dataTerlibat>
                            <gmd:abstractServices_polisi>
                                <gco:CharacterString>$request->abstractServices_polisi</gco:CharacterString>
                            </gmd:abstractServices_polisi>
                            <gmd:abstractServices_peringkatCapaian>
                                <gco:CharacterString>$request->abstractServices_peringkatCapaian</gco:CharacterString>
                            </gmd:abstractServices_peringkatCapaian>
                            <gmd:abstractServices_format>
                                <gco:CharacterString>$request->abstractServices_format</gco:CharacterString>
                            </gmd:abstractServices_format>
                            <gmd:abstractSoftware_namaPerisian>
                                <gco:CharacterString>$request->abstractSoftware_namaPerisian</gco:CharacterString>
                            </gmd:abstractSoftware_namaPerisian>
                            <gmd:abstractSoftware_versi>
                                <gco:CharacterString>$request->abstractSoftware_versi</gco:CharacterString>
                            </gmd:abstractSoftware_versi>
                            <gmd:abstractSoftware_tujuan>
                                <gco:CharacterString>$request->abstractSoftware_tujuan</gco:CharacterString>
                            </gmd:abstractSoftware_tujuan>
                            <gmd:abstractSoftware_tahunPengunaanPerisian>
                                <gco:CharacterString>$request->abstractSoftware_tahunPengunaanPerisian</gco:CharacterString>
                            </gmd:abstractSoftware_tahunPengunaanPerisian>
                            <gmd:abstractSoftware_kaedahPerolehan>
                                <gco:CharacterString>$request->abstractSoftware_kaedahPerolehan</gco:CharacterString>
                            </gmd:abstractSoftware_kaedahPerolehan>
                            <gmd:abstractSoftware_format>
                                <gco:CharacterString>$request->abstractSoftware_format</gco:CharacterString>
                            </gmd:abstractSoftware_format>
                            <gmd:abstractSoftware_pengeluar>
                                <gco:CharacterString>$request->abstractSoftware_pengeluar</gco:CharacterString>
                            </gmd:abstractSoftware_pengeluar>
                            <gmd:abstractSoftware_keupayaan>
                                <gco:CharacterString>$request->abstractSoftware_keupayaan</gco:CharacterString>
                            </gmd:abstractSoftware_keupayaan>
                            <gmd:abstractSoftware_dataTerlibat>
                                <gco:CharacterString>$request->abstractSoftware_dataTerlibat</gco:CharacterString>
                            </gmd:abstractSoftware_dataTerlibat>
                            <gmd:abstractSoftware_keperluanPerkakas>
                                <gco:CharacterString>$request->abstractSoftware_keperluanPerkakas</gco:CharacterString>
                            </gmd:abstractSoftware_keperluanPerkakas>
                            <gmd:abstractVectorData_namaData>
                                <gco:CharacterString>$request->abstractVectorData_namaData</gco:CharacterString>
                            </gmd:abstractVectorData_namaData>
                            <gmd:abstractVectorData_lokasi>
                                <gco:CharacterString>$request->abstractVectorData_lokasi</gco:CharacterString>
                            </gmd:abstractVectorData_lokasi>
                            <gmd:abstractVectorData_rumusanData>
                                <gco:CharacterString>$request->abstractVectorData_rumusanData</gco:CharacterString>
                            </gmd:abstractVectorData_rumusanData>
                            <gmd:abstractVectorData_tujuanData>
                                <gco:CharacterString>$request->abstractVectorData_tujuanData</gco:CharacterString>
                            </gmd:abstractVectorData_tujuanData>
                            <gmd:abstractVectorData_kaedahPenyediaanData>
                                <gco:CharacterString>$request->abstractVectorData_kaedahPenyediaanData</gco:CharacterString>
                            </gmd:abstractVectorData_kaedahPenyediaanData>
                            <gmd:abstractVectorData_format>
                                <gco:CharacterString>$request->abstractVectorData_format</gco:CharacterString>
                            </gmd:abstractVectorData_format>
                            <gmd:abstractVectorData_unit>
                                <gco:CharacterString>$request->abstractVectorData_unit</gco:CharacterString>
                            </gmd:abstractVectorData_unit>
                            <gmd:abstractVectorData_skala>
                                <gco:CharacterString>$request->abstractVectorData_skala</gco:CharacterString>
                            </gmd:abstractVectorData_skala>
                            <gmd:abstractVectorData_statusData>
                                <gco:CharacterString>$request->abstractVectorData_statusData</gco:CharacterString>
                            </gmd:abstractVectorData_statusData>
                            <purpose>
                                <gco:CharacterString/>
                            </purpose>
                            <credit>
                                <gco:CharacterString/>
                            </credit>
                            <status>
                                <MD_ProgressCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ProgressCode" codeListValue="completed">$request->c2_metadataStatus</MD_ProgressCode>
                            </status>
                            <pointOfContact>
                                <CI_ResponsibleParty>
                                    <organisationName>
                                        <gco:CharacterString>$request->c2_contact_agensiorganisasi</gco:CharacterString>
                                    </organisationName>
                                    <bahagianName>
                                        <gco:CharacterString>$request->c2_contact_bahagian</gco:CharacterString>
                                    </bahagianName>
                                    <individualName>
                                        <gco:CharacterString>$request->c2_contact_name</gco:CharacterString>
                                    </individualName>
                                    <gmd:positionName>
                                        <gco:CharacterString>$request->c2_position_name</gco:CharacterString>
                                    </gmd:positionName>
                                    <contactInfo>
                                        <CI_Contact>
                                            <phone>
                                                <CI_Telephone>
                                                    <voice>
                                                        <gco:CharacterString>$request->c2_contact_phone_office</gco:CharacterString>
                                                    </voice>
                                                    <gmd:facsimile>
                                                        <gco:CharacterString>$request->c2_contact_fax</gco:CharacterString>
                                                    </gmd:facsimile>
                                                </CI_Telephone>
                                            </phone>
                                            <address>
                                                <CI_Address>
                                                    <deliveryPoint>
                                                        <gco:CharacterString>$request->c2_contact_address1</gco:CharacterString>
                                                    </deliveryPoint>
                                                    <city>
                                                        <gco:CharacterString>$request->c2_contact_city</gco:CharacterString>
                                                    </city>
                                                    <administrativeArea>
                                                        <gco:CharacterString>$request->c2_contact_state</gco:CharacterString>
                                                    </administrativeArea>
                                                    <postalCode>
                                                        <gco:CharacterString>$request->c2_postal_code</gco:CharacterString>
                                                    </postalCode>
                                                    <country>
                                                        <gco:CharacterString>$request->c2_contact_country</gco:CharacterString>
                                                    </country>
                                                    <electronicMailAddress>
                                                        <gco:CharacterString>$request->c2_contact_email</gco:CharacterString>
                                                    </electronicMailAddress>
                                                </CI_Address>
                                            </address>
                                            <gmd:onlineResource>
                                                <gmd:CI_OnlineResource>
                                                    <gmd:linkage>
                                                        <gmd:URL>$request->c2_contact_website</gmd:URL>
                                                    </gmd:linkage>
                                                </gmd:CI_OnlineResource>
                                            </gmd:onlineResource>
                                            <hoursOfService>
                                                <gco:CharacterString>08.00-17.00(GMT+8)</gco:CharacterString>
                                            </hoursOfService>
                                        </CI_Contact>
                                    </contactInfo>
                                    <role>
                                        <CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="custodian">$request->c2_contact_role</CI_RoleCode>
                                    </role>
                                </CI_ResponsibleParty>
                            </pointOfContact>
                            <graphicOverview></graphicOverview>
                            <descriptiveKeywords>
                                <MD_Keywords>
                                    <keyword>
                                        <gco:CharacterString>$request->c10_keyword</gco:CharacterString>
                                    </keyword>
                                    $keywords
                                </MD_Keywords>
                            </descriptiveKeywords>
                            <spatialRepresentationType>
                                <MD_SpatialRepresentationTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_SpatialRepresentationTypeCode" codeListValue="vector">$request->c12_dataset_type</MD_SpatialRepresentationTypeCode>
                            </spatialRepresentationType>
                            <spatialResolution>
                                <MD_Resolution>
                                    <equivalentScale>
                                        <MD_RepresentativeFraction>
                                            <denominator>
                                                <gco:Integer>$request->c12_feature_scale</gco:Integer>
                                            </denominator>
                                        </MD_RepresentativeFraction>
                                    </equivalentScale>
                                    <gmd:distance>
                                        <gco:Distance>$request->c12_image_res</gco:Distance>
                                    </gmd:distance>
                                </MD_Resolution>
                            </spatialResolution>
                            <language>
                                <gco:CharacterString>$request->c12_language</gco:CharacterString>
                            </language>
                            $topicCategories
                            <gmd:scanningResolution>
                                <gco:CharacterString>$request->c4_scan_res</gco:CharacterString>
                            </gmd:scanningResolution>
                            <gmd:groundScanning>
                                <gco:Decimal>$request->c4_ground_scan</gco:Decimal>
                            </gmd:groundScanning>
                            <gmd:processLevel>
                                <gco:CharacterString>$request->c5_process_lvl</gco:CharacterString>
                            </gmd:processLevel>
                            <gmd:processResolution>
                                <gco:Decimal>$request->c5_resolution</gco:Decimal>
                            </gmd:processResolution>
                            <gmd:collectionName>
                                <gco:CharacterString>$request->c6_collection_name</gco:CharacterString>
                            </gmd:collectionName>
                            <gmd:collectionIdentification>
                                <gco:CharacterString>$request->c6_collection_id</gco:CharacterString>
                            </gmd:collectionIdentification>
                            <gmd:bandBoundry>
                                <gco:CharacterString>$request->c7_band_boundary</gco:CharacterString>
                            </gmd:bandBoundry>
                            <gmd:transferFunctionType>
                                <gco:CharacterString>$request->c7_trans_fn_type</gco:CharacterString>
                            </gmd:transferFunctionType>
                            <gmd:transmittedPolarization>
                                <gco:CharacterString>$request->c7_trans_polar</gco:CharacterString>
                            </gmd:transmittedPolarization>
                            <gmd:nominalSpatialResolution>
                                <gco:CharacterString>$request->c7_nominal_spatial_res</gco:CharacterString>
                            </gmd:nominalSpatialResolution>
                            <gmd:detectedPolarisation>
                                <gco:CharacterString>$request->c7_detected_polar</gco:CharacterString>
                            </gmd:detectedPolarisation>
                            <gmd:averageAirTemperature>
                                <gco:CharacterString>$request->c8_avg_air_temp</gco:CharacterString>
                            </gmd:averageAirTemperature>
                            <gmd:altitude>
                                <gco:CharacterString>$request->c8_altitude</gco:CharacterString>
                            </gmd:altitude>
                            <gmd:relativeHumidity>
                                <gco:CharacterString>$request->c8_relative_humid</gco:CharacterString>
                            </gmd:relativeHumidity>
                            <gmd:meteorologicalCondition>
                                <gco:CharacterString>$request->c8_meteor_cond</gco:CharacterString>
                            </gmd:meteorologicalCondition>
                            <gmd:identifier>
                                <gco:CharacterString>$request->c8_identifier</gco:CharacterString>
                            </gmd:identifier>
                            <gmd:trigger>
                                <gco:CharacterString>$request->c8_trigger</gco:CharacterString>
                            </gmd:trigger>
                            <gmd:context>
                                <gco:CharacterString>$request->c8_context</gco:CharacterString>
                            </gmd:context>
                            <gmd:sequence>
                                <gco:CharacterString>$request->c8_sequence</gco:CharacterString>
                            </gmd:sequence>
                            <gmd:EvtIdentifiertime>
                                <gco:CharacterString>$request->c8_time</gco:CharacterString>
                            </gmd:EvtIdentifiertime>
                            <gmd:typeInstrumentIdentification>
                                <gco:CharacterString>$request->c8_type</gco:CharacterString>
                            </gmd:typeInstrumentIdentification>
                            <gmd:operationIdentifier>
                                <gco:CharacterString>$request->c8_op_identifier</gco:CharacterString>
                            </gmd:operationIdentifier>
                            <gmd:operationStatus>
                                <gco:CharacterString>$request->c8_op_status</gco:CharacterString>
                            </gmd:operationStatus>
                            <gmd:operationType>
                                <gco:CharacterString>$request->c8_op_type</gco:CharacterString>
                            </gmd:operationType>
                            <gmd:operationDate>
                                <gco:Date>$request->c8_rdr_date</gco:Date>
                            </gmd:operationDate>
                            <gmd:lastAcceptableDate>
                                <gco:Date>$request->c8_last_accept_date</gco:Date>
                            </gmd:lastAcceptableDate>
                            <extent>
                                <EX_Extent>
                                    <geographicElement>
                                        <EX_GeographicBoundingBox>
                                            <gmd:westBoundLongitude>
                                                <gco:Decimal>$request->c9_west_bound_longitude</gco:Decimal>
                                            </gmd:westBoundLongitude>
                                            <gmd:eastBoundLongitude>
                                                <gco:Decimal>$request->c9_east_bound_longitude</gco:Decimal>
                                            </gmd:eastBoundLongitude>
                                            <gmd:southBoundLatitude>
                                                <gco:Decimal>$request->c9_south_bound_latitude</gco:Decimal>
                                            </gmd:southBoundLatitude>
                                            <gmd:northBoundLatitude>
                                                <gco:Decimal>$request->c9_north_bound_latitude</gco:Decimal>
                                            </gmd:northBoundLatitude>
                                        </EX_GeographicBoundingBox>
                                    </geographicElement>
                                </EX_Extent>
                            </extent>
                            <gmd:fileName>
                                <gco:CharacterString>$request->c10_file_name</gco:CharacterString>
                            </gmd:fileName>
                            <gmd:fileType>
                                <gco:CharacterString>$request->c10_file_type</gco:CharacterString>
                            </gmd:fileType>
                            <gmd:fileURL>
                                <gco:CharacterString>$request->c10_file_url</gco:CharacterString>
                            </gmd:fileURL>
                            <srv:couplingType>
                                <!-- Mandated by ISO 19119-->
                                <srv:SV_CouplingType codeList="#SV_CouplingType" codeListValue="">$request->c2_typeOfCouplingDataset</srv:SV_CouplingType>
                            </srv:couplingType>
                            <srv:containsOperations>
                                <srv:SV_OperationMetadata>
                                    <srv:operationName>
                                        <gco:CharacterString>$request->c2_operationName</gco:CharacterString>
                                    </srv:operationName>
                                </srv:SV_OperationMetadata>
                            </srv:containsOperations>
                            <supplementalInformation>
                                <gco:CharacterString/>
                            </supplementalInformation>
                            <resourceSpecificUsage>
                                <MD_Usage>
                                    <specificUsage>
                                        <gco:CharacterString/>
                                    </specificUsage>
                                    <userDeterminedLimitations>
                                        <gco:CharacterString>$request->c14_useLimitation</gco:CharacterString>
                                    </userDeterminedLimitations>
                                </MD_Usage>
                            </resourceSpecificUsage>
                            <resourceConstraints>
                                <MD_Constraints></MD_Constraints>
                                <MD_LegalConstraints>
                                    <accessConstraints>
                                        <MD_RestrictionCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="restricted">$request->c14_access_constraint</MD_RestrictionCode>
                                    </accessConstraints>
                                    <useConstraints>
                                        <MD_RestrictionCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="restricted">$request->c14_use_constraint</MD_RestrictionCode>
                                    </useConstraints>
                                </MD_LegalConstraints>
                                <MD_SecurityConstraints>
                                    <classification>
                                        <MD_ClassificationCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ClassificationCode" codeListValue="restricted">$request->c14_classification_sys</MD_ClassificationCode>
                                    </classification>
                                    <gmd:constraintsReference>$request->c14_reference</gmd:constraintsReference>
                                </MD_SecurityConstraints>
                            </resourceConstraints>
                        </MD_DataIdentification>
                    </identificationInfo>
                    <distributionInfo>
                        <MD_Distribution>
                            <distributionFormat>
                                <MD_Format>
                                    <name>
                                        <gco:CharacterString>$request->c11_dist_format</gco:CharacterString>
                                    </name>
                                    <version>
                                        <gco:CharacterString>$request->c11_version</gco:CharacterString>
                                    </version>
                                </MD_Format>
                            </distributionFormat>
                            <distributor>
                                <MD_Distributor>
                                    <distributorContact>
                                        <CI_ResponsibleParty>
                                            <organisationName>
                                                <gco:CharacterString>$request->c11_distributor</gco:CharacterString>
                                            </organisationName>
                                            <role>
                                                <CI_RoleCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode" codeListValue="custodian">custodian</CI_RoleCode>
                                            </role>
                                        </CI_ResponsibleParty>
                                    </distributorContact>
                                    <distributionOrderProcess>
                                        <MD_StandardOrderProcess>
                                            <fees>
                                                <gco:CharacterString>$request->c11_fees</gco:CharacterString>
                                            </fees>
                                            <plannedAvailableDateTime>
                                                <gco:DateTime>2013-03-05</gco:DateTime>
                                            </plannedAvailableDateTime>
                                            <orderingInstructions>
                                                <gco:CharacterString>$fileUrl</gco:CharacterString>
                                            </orderingInstructions>
                                        </MD_StandardOrderProcess>
                                    </distributionOrderProcess>
                                </MD_Distributor>
                            </distributor>
                            <transferOptions>
                                <MD_DigitalTransferOptions>
                                    <unitsOfDistribution>
                                        <gco:CharacterString>$request->c11_units_of_dist</gco:CharacterString>
                                    </unitsOfDistribution>
                                    <transferSize>
                                        <gco:Real>$request->c11_size</gco:Real>
                                    </transferSize>
                                    <onLine>
                                        <CI_OnlineResource>
                                            <linkage>
                                                <URL>$request->c11_link</URL>
                                            </linkage>
                                            <description>
                                                <gco:CharacterString>$request->c1_content_info</gco:CharacterString>
                                            </description>
                                            <function>
                                                <CI_OnLineFunctionCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue=""/>
                                            </function>
                                        </CI_OnlineResource>
                                    </onLine>
                                    <offLine>
                                        <MD_Medium>
                                            <name>
                                                <MD_MediumNameCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_MediumNameCode" codeListValue="cdRom">$request->c11_medium</MD_MediumNameCode>
                                            </name>
                                        </MD_Medium>
                                    </offLine>
                                </MD_DigitalTransferOptions>
                            </transferOptions>
                        </MD_Distribution>
                    </distributionInfo>
                    <dataQualityInfo>
                        <DQ_DataQuality>
                            <scope>
                                <DQ_Scope>
                                    <level>
                                        <MD_ScopeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue="">$request->c15_data_quality_info</MD_ScopeCode>
                                    </level>
                                </DQ_Scope>
                            </scope>
                            <lineage>
                                <LI_Lineage>
                                    <statement>
                                        <gco:CharacterString>$request->c15_data_history</gco:CharacterString>
                                    </statement>
                                </LI_Lineage>
                            </lineage>
                            <report>
                                <DQ_Element>
                                    <dateTime>
                                        <gco:Date>$request->c15_date</gco:Date>
                                    </dateTime>
                                </DQ_Element>
                                <DQ_CompletenessCommission>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:compCommissScope>
                                        <gmd:compCommissScopeItem>
                                            <gco:CharacterString>$request->c15_t1_scope</gco:CharacterString>
                                        </gmd:compCommissScopeItem>
                                    </gmd:compCommissScope>
                                    <gmd:compCommissComplLevel>
                                        <gco:CharacterString>$request->c15_t1_comply_level</gco:CharacterString>
                                    </gmd:compCommissComplLevel>
                                    <dateTime>
                                        <gco:Date>$request->c15_t1_date</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                        <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t1_result</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t1_conform_result</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_CompletenessCommission>
                                <DQ_CompletenessOmission>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:compOmissScope>
                                        <gmd:compOmissScopeItem>
                                            <gco:CharacterString>$request->c15_t1_scope_2</gco:CharacterString>
                                        </gmd:compOmissScopeItem>
                                    </gmd:compOmissScope>
                                    <gmd:compOmissComplLevel>
                                        <gco:CharacterString>$request->c15_t1_comply_level_2</gco:CharacterString>
                                    </gmd:compOmissComplLevel>
                                    <dateTime>
                                            <gco:Date>$request->c15_t1_date_2</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                            <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t1_result_2</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t1_conform_result_2</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_CompletenessOmission>
                                <DQ_ConceptualConsistency>
                                    <statement>
                                            <gco:CharacterString/>
                                    </statement>
                                    <gmd:consistConceptScope>
                                        <gmd:consistConceptScopeItem>
                                            <gco:CharacterString>$request->c15_t2_scope</gco:CharacterString>
                                        </gmd:consistConceptScopeItem>
                                    </gmd:consistConceptScope>
                                    <gmd:compOmissLevel>
                                        <gco:CharacterString>$request->c15_t2_comply_level</gco:CharacterString >
                                    </gmd:compOmissLevel>
                                    <dateTime>
                                            <gco:Date>$request->c15_t2_date</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                            <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t2_result</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t2_conform_result</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_ConceptualConsistency>
                                <DQ_DomainConsistency>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:consistDomainScope>
                                        <gmd:consistConceptScopeItem>
                                            <gco:CharacterString>$request->c15_t2_scope_2</gco:CharacterString>
                                        </gmd:consistConceptScopeItem>
                                    </gmd:consistDomainScope>
                                    <gmd:compDomainLevel>
                                        <gco:CharacterString>$request->c15_t2_comply_level_2</gco:CharacterString>
                                    </gmd:compDomainLevel>
                                    <dateTime>
                                            <gco:Date>$request->c15_t2_date_2</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                            <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t2_result_2</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                    <gco:CharacterString>$request->c15_t2_conform_result_2</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_DomainConsistency>
                                <DQ_FormatConsistency>
                                    <statement>
                                            <gco:CharacterString/>
                                    </statement>
                                    <gmd:consistFormatScope>
                                        <gmd:consistFormatScopeItem>
                                            <gco:CharacterString>$request->c15_t2_scope_3</gco:CharacterString>
                                        </gmd:consistFormatScopeItem>
                                    </gmd:consistFormatScope>
                                    <gmd:compFormatLevel>
                                        <gco:CharacterString>$request->c15_t2_comply_level_3</gco:CharacterString>
                                    </gmd:compFormatLevel>
                                    <dateTime>
                                            <gco:Date>$request->c15_t2_date_3</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                            <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t2_result_3</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t2_conform_result_3</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_FormatConsistency>
                                <DQ_TopologicalConsistency>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:consistTopoScope>
                                        <gmd:consistTopoScopeItem>
                                            <gco:CharacterString>$request->c15_t2_scope_4</gco:CharacterString>
                                        </gmd:consistTopoScopeItem>
                                    </gmd:consistTopoScope>
                                    <gmd:compTopoLevel>
                                        <gco:CharacterString>$request->c15_t2_comply_level_4</gco:CharacterString>
                                    </gmd:compTopoLevel>
                                    <dateTime>
                                        <gco:Date>$request->c15_t2_date_4</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                        <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t2_result_4</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t2_conform_result_4</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_TopologicalConsistency>
                                <DQ_AbsoluteExternalPositionalAccuracy>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:posAccAbsoluteScope>
                                        <gmd:posAccAbsoluteScopeItem>
                                            <gco:CharacterString>$request->c15_t3_scope</gco:CharacterString>
                                        </gmd:posAccAbsoluteScopeItem>
                                    </gmd:posAccAbsoluteScope>
                                    <gmd:compPosAccAbsoluteLevel>
                                        <gco:CharacterString>$request->c15_t3_comply_level</gco:CharacterString>
                                    </gmd:compPosAccAbsoluteLevel>
                                    <dateTime>
                                            <gco:Date>$request->c15_t3_date</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                            <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t3_result</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                    <gco:CharacterString>$request->c15_t3_conform_result</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_AbsoluteExternalPositionalAccuracy>
                                <DQ_RelativeInternalPositionalAccuracy>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:posAccRelativeScope>
                                        <gmd:posAccRelativeScopeItem>
                                            <gco:CharacterString>$request->c15_t3_scope_2</gco:CharacterString>
                                        </gmd:posAccRelativeScopeItem>
                                    </gmd:posAccRelativeScope>
                                    <gmd:posAccRelativeLevel>
                                        <gco:CharacterString>$request->c15_t3_comply_level_2</gco:CharacterString>
                                    </gmd:posAccRelativeLevel>
                                    <dateTime>
                                        <gco:Date>$request->c15_t3_date_2</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                        <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t3_result_2</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t3_conform_result_2</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_RelativeInternalPositionalAccuracy>
                                <DQ_GriddedDataPositionalAccuracy>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:posAccGridScope>
                                        <gmd:posAccGridScopeItem>
                                            <gco:CharacterString>$request->c15_t3_scope_3</gco:CharacterString>
                                        </gmd:posAccGridScopeItem>
                                    </gmd:posAccGridScope>
                                    <gmd:posAccGridLevel>
                                        <gco:CharacterString>$request->c15_t3_comply_level_3</gco:CharacterString>
                                    </gmd:posAccGridLevel>
                                    <dateTime>
                                        <gco:Date>$request->c15_t3_date_3</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                        <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t3_result_3</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                    <gco:CharacterString>$request->c15_t3_conform_result_3</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_GriddedDataPositionalAccuracy>
                                <DQ_AccuracyOfATimeMeasurement>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:AccuracyOfATimeMeasurementScope>
                                        <gmd:AccuracyOfATimeMeasurementItem>
                                            <gco:CharacterString>$request->c15_t4_scope</gco:CharacterString>
                                        </gmd:AccuracyOfATimeMeasurementItem>
                                    </gmd:AccuracyOfATimeMeasurementScope>
                                    <gmd:AccuracyOfATimeMeasurementLevel>
                                        <gco:CharacterString>$request->c15_t4_comply_level</gco:CharacterString>
                                    </gmd:AccuracyOfATimeMeasurementLevel>
                                    <dateTime>
                                        <gco:Date>$request->c15_t4_date</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                        <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t4_result</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t4_conform_result</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_AccuracyOfATimeMeasurement>
                                <DQ_TemporalConsistency>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:TemporalConsistencyScope>
                                        <gmd:TemporalConsistencyItem>
                                            <gco:CharacterString>$request->c15_t4_scope_2</gco:CharacterString>
                                        </gmd:TemporalConsistencyItem>
                                    </gmd:TemporalConsistencyScope>
                                    <gmd:TemporalConsistencyLevel>
                                        <gco:CharacterString>$request->c15_t4_comply_level_2</gco:CharacterString>
                                    </gmd:TemporalConsistencyLevel>
                                    <dateTime>
                                        <gco:Date>$request->c15_t4_date_2</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                        <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t4_result_2</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t4_conform_result_2</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_TemporalConsistency>
                                <DQ_TemporalValidity>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:TemporalValidityScope>
                                        <gmd:TemporalValidityItem>
                                            <gco:CharacterString>$request->c15_t4_scope_3</gco:CharacterString>
                                        </gmd:TemporalValidityItem>
                                    </gmd:TemporalValidityScope>
                                    <gmd:TemporalValidityLevel>
                                        <gco:CharacterString>$request->c15_t4_comply_level_3</gco:CharacterString>
                                    </gmd:TemporalValidityLevel>
                                    <dateTime>
                                        <gco:Date>$request->c15_t4_date_3</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                        <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t4_result_3</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t4_conform_result_3</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                        </result>
                                </DQ_TemporalValidity>
                                <DQ_ThematicClassificationCorrectness>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:ThematicClassificationCorrectnessScope>
                                        <gmd:ThematicClassificationCorrectnessItem>
                                            <gco:CharacterString>$request->c15_t5_scope</gco:CharacterString>
                                        </gmd:ThematicClassificationCorrectnessItem>
                                    </gmd:ThematicClassificationCorrectnessScope>
                                    <gmd:ThematicClassificationCorrectnessLevel>
                                        <gco:CharacterString>$request->c15_t5_comply_level</gco:CharacterString>
                                    </gmd:ThematicClassificationCorrectnessLevel>
                                        <dateTime>
                                            <gco:Date>$request->c15_t5_date</gco:Date>
                                        </dateTime>
                                        <measureDescription>
                                            <gco:CharacterString/>
                                        </measureDescription>
                                        <result>
                                            <DQ_ConformanceResult>
                                                <gmd:pass>
                                                    <gco:Boolean>$request->c15_t5_result</gco:Boolean>
                                                </gmd:pass>
                                                <explanation>
                                                    <gco:CharacterString>$request->c15_t5_conform_result</gco:CharacterString>
                                                </explanation>
                                            </DQ_ConformanceResult>
                                        </result>
                                </DQ_ThematicClassificationCorrectness>
                                <DQ_NonQuantitativeAttributeAccuracy>
                                    <statement>
                                        <gco:CharacterString/>
                                    </statement>
                                    <gmd:NonQuantitativeAttributeAccuracyScope>
                                        <gmd:NonQuantitativeAttributeAccuracyScopeItem>
                                            <gco:CharacterString>$request->c15_t5_scope_2</gco:CharacterString>
                                        </gmd:NonQuantitativeAttributeAccuracyScopeItem>
                                    </gmd:NonQuantitativeAttributeAccuracyScope>
                                    <gmd:NonQuantitativeAttributeAccuracyLevel>
                                        <gco:CharacterString>$request->c15_t5_comply_level_2</gco:CharacterString>
                                    </gmd:NonQuantitativeAttributeAccuracyLevel>
                                    <dateTime>
                                        <gco:Date>$request->c15_t5_date_2</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                        <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                               <gco:Boolean>$request->c15_t5_result_2</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t5_conform_result_2</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_NonQuantitativeAttributeAccuracy>
                                <DQ_QuantitativeAttributeAccuracy>
                                    <statement>
                                            <gco:CharacterString/>
                                    </statement>
                                    <gmd:QuantitativeAttributeAccuracyScope>
                                        <gmd:QuantitativeAttributeAccuracyItem>
                                            <gco:CharacterString>$request->c15_t5_scope_3</gco:CharacterString>
                                        </gmd:QuantitativeAttributeAccuracyItem>
                                    </gmd:QuantitativeAttributeAccuracyScope>
                                    <gmd:QuantitativeAttributeAccuracyLevel>
                                        <gco:CharacterString>$request->c15_t5_comply_level_3</gco:CharacterString>
                                    </gmd:QuantitativeAttributeAccuracyLevel>
                                    <dateTime>
                                        <gco:Date>$request->c15_t5_date_3</gco:Date>
                                    </dateTime>
                                    <measureDescription>
                                        <gco:CharacterString/>
                                    </measureDescription>
                                    <result>
                                        <DQ_ConformanceResult>
                                            <gmd:pass>
                                                <gco:Boolean>$request->c15_t5_result_3</gco:Boolean>
                                            </gmd:pass>
                                            <explanation>
                                                <gco:CharacterString>$request->c15_t5_conform_result_3</gco:CharacterString>
                                            </explanation>
                                        </DQ_ConformanceResult>
                                    </result>
                                </DQ_QuantitativeAttributeAccuracy>
                            </report>
                        </DQ_DataQuality>
                    </dataQualityInfo>
                    $custom_inputs
                </MD_Metadata>
        XML;
        return $xml;
    }
}